### ISSUE TITLE
keep http params sigstore java user-agent up to date.

### ISSUE THREAD

**Issue by bobcallaway** [sigstore/sigstore-java#100]
**Description**

It would be good for clients to be able to specify a `User-Agent` header on HTTP requests to sigstore services.

@loosebazooka

**Comment by loosebazooka** [comment]
this is already possible using httpParams: https://github.com/sigstore/sigstore-java/blob/main/sigstore-java/src/main/java/dev/sigstore/http/HttpParams.java

However we don't inject the version into there which is probably something we *should* do. @vlsi any ideas for injecting compile time vars (rather than reading the jar manifest?)

**Comment by vlsi** [comment]
WDYT of generating a class with the compile-time constants?

**Comment by vlsi** [comment]
I can replicate something like https://github.com/pgjdbc/pgjdbc/blob/master/pgjdbc/src/main/version/org/postgresql/util/DriverInfo.java

**Comment by loosebazooka** [comment]
Yeah, lets do that. Let me know if you want someone else to pick it up. I can also do it.

**Comment by loosebazooka** [comment]
this was fixed with https://github.com/sigstore/sigstore-java/pull/728
