### ISSUE TITLE
process isolation in worker mechanism disables browser window from appearing

### ISSUE THREAD

**Issue by loosebazooka** [sigstore/sigstore-java#337]
I've isolated the issue with local testing, but I think it actually holds true for anyone potentially using the gradle plugin that a browser wont pop up:

https://github.com/sigstore/sigstore-java/blob/main/sigstore-gradle/sigstore-gradle-sign-base-plugin/src/main/kotlin/dev/sigstore/sign/tasks/SigstoreSignFilesTask.kt#L196

It appears to have something to do with process isolation, if this is switched back to classpath isolation, things work as intended and the browser pops up (obviously with other oom concerns).

FYI @vlsi

**Comment by szpak** [comment]
Maybe due to:
https://github.com/sigstore/sigstore-java/blob/d2e1c8c8c350a2eb30b113a6958cb31931cb34f3/sigstore-gradle/sigstore-gradle-sign-base-plugin/src/main/kotlin/dev/sigstore/sign/tasks/SigstoreSignFilesTask.kt#L65-L68

and:
https://github.com/sigstore/sigstore-java/blob/d2e1c8c8c350a2eb30b113a6958cb31931cb34f3/sigstore-gradle/sigstore-gradle-sign-base-plugin/src/main/kotlin/dev/sigstore/sign/tasks/SigstoreSignFilesTask.kt#L200-L202

there are some other ENVs needed to open the browser window filtered out?

**Comment by loosebazooka** [comment]
good call @szpak looks like a few more envs are needed. @vlsi, why don't we just pass the whole env in?

**Comment by vlsi** [comment]
Frankly speaking, I've no strong opinion here.
sigstore-java has a lot of dependencies, so if we expose env vars, they become available to all the third-party libs.

On the other hand, I see why "just pass all env vars" might be desired.
If you incline passing all the envs is safe enough, we can probably revert that: https://github.com/sigstore/sigstore-java/pull/300/files#diff-8ae77bd1cfd6640249e07c60f62f76b78be1f37c9ef136c1c22517c4abcf37b0L127

**Comment by loosebazooka** [comment]
Yeah, lets revert that line for now and move forward. We can fine tune isolation again at a future time?
